version: '2'
services:
    goonatira-app:
        image: goonatira
        external_links:
            - goonatira-postgresql:postgresql
            - goonatira-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/GoonaTira
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    goonatira-postgresql:
        extends:
            file: postgresql.yml
            service: goonatira-postgresql
    goonatira-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: goonatira-elasticsearch
